from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from .constants import DEFAULT_SEED, MAX_CONCURRENT_SCENARIOS, MAX_RESEARCH_RESOURCE_LOAD
from .types import OverridePolicy, RuntimeEnvironment


@dataclass(frozen=True)
class SettingDefinition:
    key: str
    value_type: type
    unit: str
    default: Any
    minimum: float | int | None = None
    maximum: float | int | None = None
    required: bool = True
    safety_critical: bool = False
    override_policy: OverridePolicy = OverridePolicy.ALLOW
    choices: tuple[Any, ...] = ()
    deprecated_replacement: str | None = None


def _d(key: str, kind: type, unit: str, default: Any, **kwargs: Any) -> SettingDefinition:
    return SettingDefinition(key, kind, unit, default, **kwargs)


# The active schema is intentionally limited to fictional research and generic
# computational bounds. Market-execution tuning is not present in this build.
SETTING_DEFINITIONS: tuple[SettingDefinition, ...] = (
    _d("general.enabled", bool, "boolean", True),
    _d("general.configuration_name", str, "text", "AMRTE Research"),
    _d("general.configuration_description", str, "text", "Fictional research configuration"),
    _d("general.instance_id", str, "identifier", "AMRTE-RESEARCH-001"),
    _d("general.scheduler_seconds", int, "seconds", 60, minimum=1, maximum=86400),
    _d("general.deterministic", bool, "boolean", True, safety_critical=True,
       override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("general.strict_validation", bool, "boolean", True, safety_critical=True,
       override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("runtime.mode", str, "enum", "RESEARCH",
       choices=tuple(item.name for item in RuntimeEnvironment if item is not RuntimeEnvironment.UNKNOWN)),
    _d("runtime.allow_hot_reload", bool, "boolean", False, safety_critical=True,
       override_policy=OverridePolicy.DENY),
    _d("research.base_unit", str, "fictional-unit", "CREDITS"),
    _d("research.starting_units", float, "fictional-unit", 1000.0, minimum=0.0, maximum=1_000_000.0),
    _d("research.minimum_units", float, "fictional-unit", 0.0, minimum=0.0, maximum=1_000_000.0),
    _d("research.accounting_mode", str, "enum", "ABSTRACT", choices=("ABSTRACT",)),
    _d("instruments.enabled", tuple, "identifiers", ("FICTIONAL_ALPHA",)),
    _d("timeframes.context", str, "timeframe", "H4", choices=("M15", "H1", "H4", "D1")),
    _d("timeframes.strategy", str, "timeframe", "H1", choices=("M15", "H1", "H4", "D1")),
    _d("timeframes.execution", str, "timeframe", "M15", choices=("M15", "H1", "H4", "D1")),
    _d("research.minimum_quality_score", float, "ratio", 0.70, minimum=0.0, maximum=1.0),
    _d("research.max_concurrent_scenarios", int, "count", 3, minimum=1,
       maximum=MAX_CONCURRENT_SCENARIOS),
    _d("research.max_resource_load", float, "ratio", 0.50, minimum=0.0,
       maximum=MAX_RESEARCH_RESOURCE_LOAD),
    _d("research.seed", int, "integer", DEFAULT_SEED, minimum=0, maximum=2**32 - 1),
    _d("protection.enabled", bool, "boolean", True, safety_critical=True,
       override_policy=OverridePolicy.DENY),
    _d("protection.fail_closed", bool, "boolean", True, safety_critical=True,
       override_policy=OverridePolicy.DENY),
    _d("protection.manual_suspension", bool, "boolean", False),
    _d("logging.minimum_severity", str, "enum", "INFO",
       choices=("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL")),
    _d("logging.configuration_audit", bool, "boolean", True, safety_critical=True,
       override_policy=OverridePolicy.DENY),
    _d("logging.verbosity", str, "enum", "NORMAL",
       choices=("MINIMAL", "NORMAL", "VERBOSE", "DEBUG")),
    _d("logging.maximum_file_bytes", int, "bytes", 1000000, minimum=1024, maximum=100000000),
    _d("logging.maximum_total_bytes", int, "bytes", 5000000, minimum=2048, maximum=1000000000),
    _d("logging.rotation_count", int, "count", 3, minimum=1, maximum=50),
    _d("logging.maximum_buffered_events", int, "count", 1000, minimum=10, maximum=100000),
    _d("backtest.deterministic", bool, "boolean", True, safety_critical=True,
       override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("backtest.dataset_id", str, "identifier", "FICTIONAL_DATASET"),
    _d("backtest.no_look_ahead", bool, "boolean", True, safety_critical=True,
       override_policy=OverridePolicy.DENY),
    _d("market_data.provider_type", str, "enum", "DETERMINISTIC_OFFLINE",
       choices=("DETERMINISTIC_OFFLINE",)),
    _d("market_data.dataset_reference", str, "portable-path", "data/imported"),
    _d("market_data.cache_directory", str, "portable-path", "data/cache"),
    _d("market_data.temporary_directory", str, "portable-path", "runtime/temp"),
    _d("market_data.timestamp_policy", str, "enum", "UTC_STRICT", choices=("UTC_STRICT",)),
    _d("market_data.minimum_history", int, "bars", 1, minimum=1, maximum=1000000),
    _d("market_data.stale_multiplier", float, "cadence-multiple", 2.0, minimum=1.0, maximum=100.0),
    _d("market_data.anomaly_ratio", float, "ratio", 0.25, minimum=0.001, maximum=100.0),
    _d("market_data.maximum_memory_cache_entries", int, "entries", 128, minimum=1, maximum=100000),
    _d("market_data.maximum_local_cache_bytes", int, "bytes", 10000000, minimum=0, maximum=1000000000),
    _d("market_data.cache_retention_seconds", int, "seconds", 86400, minimum=0, maximum=31536000),
    _d("market_data.gap_policy", str, "enum", "UNKNOWN_IS_UNTRUSTED", choices=("UNKNOWN_IS_UNTRUSTED",)),
    _d("market_data.strict_integrity", bool, "boolean", True, safety_critical=True,
       override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("structure.swing_left_bars", int, "bars", 2, minimum=1, maximum=100),
    _d("structure.swing_right_bars", int, "bars", 2, minimum=1, maximum=100),
    _d("structure.swing_tie_policy", str, "enum", "FIRST",
       choices=("FIRST", "LAST", "CLUSTER", "REJECT_AMBIGUOUS")),
    _d("structure.equality_tolerance_method", str, "enum", "PERCENTAGE",
       choices=("ABSOLUTE_PRICE", "PERCENTAGE", "NORMALIZED_DISTANCE")),
    _d("structure.equality_tolerance", float, "ratio", 0.001, minimum=0.0, maximum=1.0),
    _d("structure.minimum_evidence", int, "events", 2, minimum=1, maximum=100),
    _d("structure.direction_lookback", int, "swings", 6, minimum=2, maximum=1000),
    _d("structure.bos_confirmation", str, "enum", "CLOSE_BREAK",
       choices=("WICK_BREAK", "CLOSE_BREAK", "MULTI_CLOSE_CONFIRMATION")),
    _d("structure.bos_minimum_penetration", float, "price", 0.0, minimum=0.0, maximum=1000000.0),
    _d("structure.bos_confirmation_bars", int, "bars", 1, minimum=1, maximum=20),
    _d("structure.consolidation_window", int, "bars", 8, minimum=2, maximum=10000),
    _d("structure.consolidation_entry_threshold", float, "ratio", 0.03, minimum=0.0, maximum=1.0),
    _d("structure.consolidation_exit_threshold", float, "ratio", 0.05, minimum=0.0, maximum=1.0),
    _d("structure.zone_width_method", str, "enum", "PERCENTAGE", choices=("FIXED_DISTANCE", "PERCENTAGE", "STRUCTURAL_CLUSTER")),
    _d("structure.zone_width", float, "ratio", 0.002, minimum=0.0, maximum=1.0),
    _d("structure.zone_merge_threshold", float, "ratio", 0.001, minimum=0.0, maximum=1.0),
    _d("structure.zone_expiration_bars", int, "bars", 100, minimum=1, maximum=100000),
    _d("structure.maximum_active_zones", int, "zones", 20, minimum=1, maximum=1000),
    _d("structure.maximum_swings", int, "swings", 200, minimum=2, maximum=100000),
    _d("structure.alignment_weights", tuple, "weights", (0.5, 0.3, 0.2)),
    _d("structure.strict", bool, "boolean", True, safety_critical=True,
       override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("features.ema_periods", tuple, "bars", (20, 50, 200)),
    _d("features.atr_period", int, "bars", 14, minimum=1, maximum=10000),
    _d("features.adx_period", int, "bars", 14, minimum=1, maximum=10000),
    _d("features.rsi_period", int, "bars", 14, minimum=1, maximum=10000),
    _d("features.macd_fast", int, "bars", 12, minimum=1, maximum=10000),
    _d("features.macd_slow", int, "bars", 26, minimum=2, maximum=10000),
    _d("features.macd_signal", int, "bars", 9, minimum=1, maximum=10000),
    _d("features.bollinger_period", int, "bars", 20, minimum=2, maximum=10000),
    _d("features.bollinger_deviation", float, "population-standard-deviations", 2.0, minimum=0.001, maximum=100.0),
    _d("features.price_source", str, "enum", "CLOSE", choices=("OPEN","HIGH","LOW","CLOSE","MEDIAN_PRICE","TYPICAL_PRICE","WEIGHTED_CLOSE")),
    _d("features.slope_lookback", int, "bars", 5, minimum=1, maximum=10000),
    _d("features.volatility_window", int, "returns", 20, minimum=2, maximum=10000),
    _d("features.volatility_return_type", str, "enum", "LOG_RETURN", choices=("SIMPLE_RETURN","LOG_RETURN")),
    _d("features.volatility_percentile_window", int, "observations", 100, minimum=2, maximum=100000),
    _d("features.minimum_samples", int, "observations", 2, minimum=1, maximum=100000),
    _d("features.bar_state", str, "enum", "CLOSED_BAR", choices=("CLOSED_BAR","CURRENT_FORMING_BAR")),
    _d("features.maximum_cache_entries", int, "entries", 512, minimum=1, maximum=100000),
    _d("features.strict", bool, "boolean", True, safety_critical=True,
       override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("regime.trend_threshold", float, "score-0-100", 60.0, minimum=0.0, maximum=100.0),
    _d("regime.range_threshold", float, "score-0-100", 60.0, minimum=0.0, maximum=100.0),
    _d("regime.breakout_threshold", float, "score-0-100", 65.0, minimum=0.0, maximum=100.0),
    _d("regime.transition_threshold", float, "score-0-100", 55.0, minimum=0.0, maximum=100.0),
    _d("regime.abnormal_threshold", float, "score-0-100", 70.0, minimum=0.0, maximum=100.0),
    _d("regime.minimum_confidence", float, "score-0-100", 50.0, minimum=0.0, maximum=100.0),
    _d("regime.minimum_classification_margin", float, "score-0-100", 8.0, minimum=0.0, maximum=100.0),
    _d("regime.entry_threshold", float, "score-0-100", 60.0, minimum=0.0, maximum=100.0),
    _d("regime.exit_threshold", float, "score-0-100", 45.0, minimum=0.0, maximum=100.0),
    _d("regime.confirmation_observations", int, "observations", 2, minimum=1, maximum=1000),
    _d("regime.minimum_persistence", int, "observations", 1, minimum=1, maximum=1000),
    _d("regime.cooldown_observations", int, "observations", 1, minimum=0, maximum=1000),
    _d("regime.unknown_grace_observations", int, "observations", 1, minimum=0, maximum=1000),
    _d("regime.maximum_history", int, "entries", 100, minimum=1, maximum=100000),
    _d("regime.timeframe_weights", tuple, "weights", (0.5, 0.3, 0.2)),
    _d("regime.strict", bool, "boolean", True, safety_critical=True,
       override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("time.reference_timezone", str, "iana-timezone", "UTC"),
    _d("time.data_source_timezone", str, "iana-timezone", "UTC"),
    _d("time.trading_day_timezone", str, "iana-timezone", "America/New_York"),
    _d("time.trading_day_boundary", str, "HH:MM", "17:00"),
    _d("time.trading_week_timezone", str, "iana-timezone", "America/New_York"),
    _d("time.trading_week_start_weekday", int, "weekday-0-6", 6, minimum=0, maximum=6),
    _d("time.trading_week_start", str, "HH:MM", "17:00"),
    _d("time.session_definitions", tuple, "session-definitions", ()),
    _d("time.friday_cutoff", str, "HH:MM", "16:00"),
    _d("time.monday_reopen_delay_minutes", int, "minutes", 30, minimum=0, maximum=1440),
    _d("time.minimum_reopen_observations", int, "bars", 1, minimum=0, maximum=100000),
    _d("time.rollover_windows", tuple, "rollover-definitions", ()),
    _d("time.custom_sessions", tuple, "session-definitions", ()),
    _d("time.instrument_session_overrides", tuple, "override-definitions", ()),
    _d("time.strategy_family_session_eligibility", tuple, "eligibility-definitions", ()),
    _d("time.calendar_policy", str, "enum", "STRICT_UNKNOWN", choices=("STRICT_UNKNOWN","EXPLICIT_WEEKDAY_FALLBACK","CONFIGURED")),
    _d("time.strict", bool, "boolean", True, safety_critical=True,
       override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("time.maximum_cache_entries", int, "entries", 512, minimum=1, maximum=100000),
    _d("time.maximum_clock_jump_minutes", int, "minutes", 1440, minimum=1, maximum=525600),
    _d("events.provider_type", str, "enum", "DETERMINISTIC_OFFLINE", choices=("DETERMINISTIC_OFFLINE",)),
    _d("events.dataset_reference", str, "portable-path", "data/events"),
    _d("events.unknown_importance_policy", str, "enum", "HIGH", choices=("MEDIUM","HIGH","CRITICAL")),
    _d("events.low_windows", tuple, "minutes-pre-blackout-before-blackout-after-post-stabilization", (30,5,5,5,10)),
    _d("events.medium_windows", tuple, "minutes-pre-blackout-before-blackout-after-post-stabilization", (60,10,10,10,20)),
    _d("events.high_windows", tuple, "minutes-pre-blackout-before-blackout-after-post-stabilization", (120,15,15,15,30)),
    _d("events.critical_windows", tuple, "minutes-pre-blackout-before-blackout-after-post-stabilization", (180,30,30,30,60)),
    _d("events.maximum_cache_entries", int, "entries", 256, minimum=1, maximum=100000),
    _d("events.maximum_history", int, "snapshots", 100, minimum=1, maximum=100000),
    _d("events.strict", bool, "boolean", True, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("strategies.framework_enabled", bool, "boolean", True),
    _d("strategies.allowed_instruments", tuple, "identifiers", ("FICTIONAL_ALPHA",)),
    _d("strategies.cooldown_observations", int, "observations", 0, minimum=0, maximum=100000),
    _d("strategies.candidate_ttl_minutes", int, "minutes", 60, minimum=1, maximum=525600),
    _d("strategies.maximum_cache_entries", int, "entries", 256, minimum=1, maximum=100000),
    _d("strategies.maximum_history", int, "entries", 100, minimum=1, maximum=100000),
    _d("strategies.strict", bool, "boolean", True, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("strategies.s1_trend_pullback.enabled", bool, "boolean", True),
    _d("strategies.s1_trend_pullback.context_timeframe", str, "timeframe", "H4", choices=("M15","H1","H4","D1")),
    _d("strategies.s1_trend_pullback.strategy_timeframe", str, "timeframe", "H1", choices=("M15","H1","H4","D1")),
    _d("strategies.s1_trend_pullback.execution_timeframe", str, "timeframe", "M15", choices=("M15","H1","H4","D1")),
    _d("strategies.s1_trend_pullback.minimum_regime_confidence", float, "score-0-100", 45.0, minimum=0.0, maximum=100.0),
    _d("strategies.s1_trend_pullback.minimum_structure_confidence", float, "score-0-100", 45.0, minimum=0.0, maximum=100.0),
    _d("strategies.s1_trend_pullback.minimum_adx", float, "score-0-100", 20.0, minimum=0.0, maximum=100.0),
    _d("strategies.s1_trend_pullback.minimum_trend_persistence", int, "observations", 1, minimum=1, maximum=10000),
    _d("strategies.s1_trend_pullback.minimum_pullback_depth", float, "ATR-multiple", 0.10, minimum=0.0, maximum=100.0),
    _d("strategies.s1_trend_pullback.maximum_pullback_depth", float, "ATR-multiple", 3.0, minimum=0.0, maximum=100.0),
    _d("strategies.s1_trend_pullback.minimum_pullback_duration", int, "observations", 1, minimum=1, maximum=10000),
    _d("strategies.s1_trend_pullback.maximum_pullback_duration", int, "observations", 12, minimum=1, maximum=10000),
    _d("strategies.s1_trend_pullback.minimum_resumption_strength", float, "ATR-multiple", 0.10, minimum=0.0, maximum=100.0),
    _d("strategies.s1_trend_pullback.maximum_volatility_expansion", float, "ratio", 3.0, minimum=0.001, maximum=100.0),
    _d("strategies.s1_trend_pullback.confirmation_bars", int, "closed-bars", 1, minimum=1, maximum=1000),
    _d("strategies.s1_trend_pullback.candidate_ttl_minutes", int, "minutes", 60, minimum=1, maximum=525600),
    _d("strategies.s1_trend_pullback.maximum_history", int, "entries", 100, minimum=1, maximum=100000),
    _d("strategies.s1_trend_pullback.maximum_cache_entries", int, "entries", 256, minimum=1, maximum=100000),
    _d("strategies.s1_trend_pullback.closed_bar_only", bool, "boolean", True, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("strategies.s1_trend_pullback.scoring_model_id", str, "identifier", "AMRTE_TREND_RESEARCH_SCORE"),
    _d("features.temporal_maximum_observations", int, "observations", 512, minimum=1, maximum=100000),
    _d("features.temporal_maximum_cache_entries", int, "entries", 256, minimum=1, maximum=100000),
    _d("regime.compression_minimum_bars", int, "bars", 3, minimum=1, maximum=10000),
    _d("regime.compression_maximum_lookback", int, "bars", 12, minimum=1, maximum=100000),
    _d("regime.compression_minimum_persistence", int, "bars", 2, minimum=1, maximum=10000),
    _d("strategies.s2.enabled", bool, "boolean", True),
    _d("strategies.s2.immediate_enabled", bool, "boolean", True),
    _d("strategies.s2.retest_enabled", bool, "boolean", True),
    _d("strategies.s2.context_timeframe", str, "timeframe", "H4", choices=("M15","H1","H4","D1")),
    _d("strategies.s2.breakout_timeframe", str, "timeframe", "H1", choices=("M15","H1","H4","D1")),
    _d("strategies.s2.confirmation_timeframe", str, "timeframe", "M15", choices=("M15","H1","H4","D1")),
    _d("strategies.s2.strict_compression", bool, "boolean", True),
    _d("strategies.s2.minimum_compression_score", float, "score-0-100", 70.0, minimum=0.0, maximum=100.0),
    _d("strategies.s2.minimum_penetration", float, "normalized-distance", 0.0, minimum=0.0, maximum=100.0),
    _d("strategies.s2.minimum_expansion_ratio", float, "ratio", 1.1, minimum=0.001, maximum=100.0),
    _d("strategies.s2.minimum_displacement", float, "ATR-multiple", 0.10, minimum=0.0, maximum=100.0),
    _d("strategies.s2.wick_break_allowed", bool, "boolean", False),
    _d("strategies.s2.confirmation_bars", int, "closed-bars", 1, minimum=1, maximum=1000),
    _d("strategies.s2.minimum_retest_delay", int, "bars", 1, minimum=0, maximum=10000),
    _d("strategies.s2.maximum_retest_bars", int, "bars", 8, minimum=1, maximum=10000),
    _d("strategies.s2.retest_tolerance", float, "normalized-distance", 0.5, minimum=0.0, maximum=100.0),
    _d("strategies.s2.maximum_history", int, "entries", 100, minimum=1, maximum=100000),
    _d("strategies.s3.enabled", bool, "boolean", True),
    _d("strategies.s3.context_timeframe", str, "timeframe", "H4", choices=("M15","H1","H4","D1")),
    _d("strategies.s3.range_timeframe", str, "timeframe", "H1", choices=("M15","H1","H4","D1")),
    _d("strategies.s3.confirmation_timeframe", str, "timeframe", "M15", choices=("M15","H1","H4","D1")),
    _d("strategies.s3.strict_range", bool, "boolean", True),
    _d("strategies.s3.minimum_observations", int, "observations", 2, minimum=1, maximum=10000),
    _d("strategies.s3.minimum_boundary_tests", int, "tests", 1, minimum=1, maximum=10000),
    _d("strategies.s3.minimum_normalized_width", float, "normalized-distance", 0.25, minimum=0.000001, maximum=100.0),
    _d("strategies.s3.maximum_normalized_width", float, "normalized-distance", 8.0, minimum=0.000001, maximum=100.0),
    _d("strategies.s3.lower_extreme", float, "range-position", 0.10, minimum=0.0, maximum=0.499999),
    _d("strategies.s3.upper_extreme", float, "range-position", 0.90, minimum=0.500001, maximum=1.0),
    _d("strategies.s3.maximum_excursion", float, "range-position", 0.35, minimum=0.0, maximum=10.0),
    _d("strategies.s3.rsi_lower", float, "score-0-100", 35.0, minimum=0.0, maximum=49.999),
    _d("strategies.s3.rsi_upper", float, "score-0-100", 65.0, minimum=50.001, maximum=100.0),
    _d("strategies.s3.require_rsi", bool, "boolean", False),
    _d("strategies.s3.require_bollinger", bool, "boolean", True),
    _d("strategies.s3.wick_rejection_allowed", bool, "boolean", False),
    _d("strategies.s3.minimum_wick_ratio", float, "ratio", 0.45, minimum=0.0, maximum=1.0),
    _d("strategies.s3.minimum_reversion_displacement", float, "ATR-multiple", 0.05, minimum=0.0, maximum=100.0),
    _d("strategies.s3.candidate_ttl_minutes", int, "minutes", 60, minimum=1, maximum=525600),
    _d("strategies.s3.cooldown_observations", int, "observations", 1, minimum=0, maximum=10000),
    _d("strategies.s3.maximum_history", int, "entries", 100, minimum=1, maximum=100000),
    _d("strategies.s3.maximum_cache_entries", int, "entries", 256, minimum=1, maximum=100000),
    _d("strategy_arbitration.enabled", bool, "boolean", True),
    _d("strategy_arbitration.policy", str, "enum", "HYBRID_CONSERVATIVE", choices=("REJECT_CONFLICTS","REGIME_NATIVE_PRIORITY","CONFIDENCE_PRIORITY","QUALITY_PRIORITY","HYBRID_CONSERVATIVE","COMPATIBILITY_ONLY","CUSTOM_CONFIGURED")),
    _d("strategy_arbitration.require_same_intelligence_snapshot", bool, "boolean", True, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("strategy_arbitration.reject_expired", bool, "boolean", True, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("strategy_arbitration.allow_degraded", bool, "boolean", False),
    _d("strategy_arbitration.regime_native_priority", bool, "boolean", True),
    _d("strategy_arbitration.minimum_confidence", float, "score-0-100", 0.0, minimum=0.0, maximum=100.0),
    _d("strategy_arbitration.minimum_quality", float, "score-0-100", 0.0, minimum=0.0, maximum=100.0),
    _d("strategy_arbitration.minimum_completeness", float, "score-0-100", 50.0, minimum=0.0, maximum=100.0),
    _d("strategy_arbitration.maximum_uncertainty", float, "score-0-100", 80.0, minimum=0.0, maximum=100.0),
    _d("strategy_arbitration.minimum_confidence_difference", float, "score-0-100", 10.0, minimum=0.0, maximum=100.0),
    _d("strategy_arbitration.minimum_quality_difference", float, "score-0-100", 10.0, minimum=0.0, maximum=100.0),
    _d("strategy_arbitration.tie_tolerance", float, "score-0-100", 2.0, minimum=0.0, maximum=100.0),
    _d("strategy_arbitration.combination_mode", str, "enum", "ALLOW_EXPLICIT_PAIRS_ONLY", choices=("ALLOW_NONE","ALLOW_SAME_DIRECTION_COMPATIBLE","ALLOW_EXPLICIT_PAIRS_ONLY")),
    _d("strategy_arbitration.maximum_groups", int, "entries", 256, minimum=1, maximum=100000),
    _d("strategy_arbitration.maximum_decisions", int, "entries", 256, minimum=1, maximum=100000),
    _d("strategy_arbitration.maximum_conflicts", int, "entries", 512, minimum=1, maximum=100000),
    _d("strategy_arbitration.maximum_cache_entries", int, "entries", 256, minimum=1, maximum=100000),
    _d("risk.per_hypothesis.enabled", bool, "boolean", True),
    _d("risk.per_hypothesis.default_research_capital", float, "fictional-research-capital", 10000.0, minimum=0.0, maximum=1e15),
    _d("risk.per_hypothesis.base_risk_fraction", float, "fraction", 0.01, minimum=0.0, maximum=1.0),
    _d("risk.per_hypothesis.minimum_invalidation_distance", float, "normalized-distance", 0.10, minimum=0.000000001, maximum=1e9),
    _d("risk.per_hypothesis.maximum_invalidation_distance", float, "normalized-distance", 10.0, minimum=0.000000001, maximum=1e9),
    _d("risk.per_hypothesis.cost_buffer_enabled", bool, "boolean", False),
    _d("risk.per_hypothesis.missing_cost_policy", str, "enum", "NOT_REQUIRED", choices=("BLOCK","USE_CONFIGURED_CONSERVATIVE_BUFFER","NOT_REQUIRED")),
    _d("risk.per_hypothesis.conservative_cost_buffer", float, "normalized-risk-unit", 0.0, minimum=0.0, maximum=1e15),
    _d("risk.per_hypothesis.minimum_exposure", float, "simulated-exposure-unit", 0.01, minimum=0.0, maximum=1e15),
    _d("risk.per_hypothesis.maximum_exposure", float, "simulated-exposure-unit", 100.0, minimum=0.0, maximum=1e15),
    _d("risk.per_hypothesis.exposure_step", float, "simulated-exposure-unit", 0.01, minimum=0.000000001, maximum=1e15),
    _d("risk.per_hypothesis.multiple_compatible_policy", str, "enum", "BLOCK", choices=("BLOCK","SHARED_BUDGET")),
    _d("risk.per_hypothesis.modifier_composition", str, "enum", "MIN", choices=("MIN","MULTIPLICATIVE")),
    _d("risk.per_hypothesis.precision", int, "decimal-digits", 28, minimum=8, maximum=50),
    _d("risk.per_hypothesis.maximum_decisions", int, "entries", 256, minimum=1, maximum=100000),
    _d("risk.per_hypothesis.maximum_budgets", int, "entries", 256, minimum=1, maximum=100000),
    _d("risk.per_hypothesis.maximum_cache_entries", int, "entries", 256, minimum=1, maximum=100000),
    _d("risk.adaptive.enabled", bool, "boolean", True),
    _d("risk.adaptive.allow_risk_amplification", bool, "boolean", False, safety_critical=True, override_policy=OverridePolicy.DENY),
    _d("risk.adaptive.maximum_modifier", float, "fraction", 1.0, minimum=0.0, maximum=1.0, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("risk.adaptive.composition_mode", str, "enum", "MULTIPLICATIVE_RESTRICTIVE", choices=("MULTIPLICATIVE_RESTRICTIVE","MINIMUM_MODIFIER")),
    _d("risk.adaptive.overlap_policy", str, "enum", "MOST_RESTRICTIVE_ONLY", choices=("MOST_RESTRICTIVE_ONLY","PRIMARY_SOURCE_ONLY","ALLOW_MULTIPLICATIVE_IF_INDEPENDENT")),
    _d("risk.adaptive.system_maximum_fraction", float, "fraction", 0.02, minimum=0.0, maximum=1.0, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("risk.adaptive.profile_maximum_fraction", float, "fraction", 0.02, minimum=0.0, maximum=1.0),
    _d("risk.adaptive.strategy_family_maximum_fraction", float, "fraction", 0.02, minimum=0.0, maximum=1.0),
    _d("risk.adaptive.strategy_maximum_fraction", float, "fraction", 0.02, minimum=0.0, maximum=1.0),
    _d("risk.adaptive.instrument_maximum_fraction", float, "fraction", 0.02, minimum=0.0, maximum=1.0),
    _d("risk.adaptive.per_hypothesis_maximum_fraction", float, "fraction", 0.02, minimum=0.0, maximum=1.0),
    _d("risk.adaptive.portfolio_missing_policy", str, "enum", "NEUTRAL_IF_NOT_REQUIRED", choices=("NEUTRAL_IF_NOT_REQUIRED","RESTRICT","BLOCK")),
    _d("risk.adaptive.protection_missing_policy", str, "enum", "NEUTRAL_IF_NOT_REQUIRED", choices=("NEUTRAL_IF_NOT_REQUIRED","RESTRICT","BLOCK")),
    _d("risk.adaptive.recovery_confirmation_observations", int, "observations", 2, minimum=1, maximum=10000),
    _d("risk.adaptive.cooldown_seconds", int, "seconds", 300, minimum=0, maximum=31536000),
    _d("risk.adaptive.maximum_modifier_results", int, "entries", 256, minimum=1, maximum=100000),
    _d("risk.adaptive.maximum_decisions", int, "entries", 256, minimum=1, maximum=100000),
    _d("risk.adaptive.maximum_transitions", int, "entries", 256, minimum=1, maximum=100000),
    _d("risk.adaptive.maximum_cache_entries", int, "entries", 256, minimum=1, maximum=100000),
    _d("risk.invalidation.enabled", bool, "boolean", True),
    _d("risk.invalidation.require_authoritative_invalidation", bool, "boolean", True, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("risk.invalidation.minimum_distance", float, "normalized-distance", 0.10, minimum=0.000000001, maximum=1e9),
    _d("risk.invalidation.maximum_distance", float, "normalized-distance", 10.0, minimum=0.000000001, maximum=1e9),
    _d("risk.invalidation.below_minimum_policy", str, "enum", "REJECT", choices=("REJECT","WIDEN_TO_MINIMUM_IF_THESIS_VALID")),
    _d("risk.invalidation.atr_multiplier", float, "ATR-multiple", 1.5, minimum=0.0, maximum=1000.0),
    _d("risk.invalidation.friction_enabled", bool, "boolean", False),
    _d("risk.invalidation.friction_source", str, "enum", "NONE", choices=("CONFIGURED_NORMALIZED_BUFFER","HISTORICAL_OFFLINE_FRICTION_SERIES","SYNTHETIC_FIXTURE","NONE")),
    _d("risk.invalidation.missing_friction_policy", str, "enum", "NOT_REQUIRED", choices=("NOT_REQUIRED","USE_CONSERVATIVE_CONFIGURED_VALUE","BLOCK")),
    _d("risk.invalidation.conservative_friction_buffer", float, "normalized-distance", 0.0, minimum=0.0, maximum=1e9),
    _d("risk.invalidation.volatility_adjustment_enabled", bool, "boolean", False),
    _d("risk.invalidation.maximum_volatility_allowance", float, "normalized-distance", 1.0, minimum=0.0, maximum=1e9),
    _d("risk.invalidation.default_condition", str, "enum", "CLOSE_BEYOND", choices=("TOUCH","CLOSE_BEYOND","MULTI_CLOSE_BEYOND","STRUCTURAL_CONFIRMATION","STRATEGY_DEFINED")),
    _d("risk.invalidation.multi_close_count", int, "observations", 2, minimum=1, maximum=1000),
    _d("risk.invalidation.maximum_candidates", int, "entries", 256, minimum=1, maximum=100000),
    _d("risk.invalidation.maximum_decisions", int, "entries", 256, minimum=1, maximum=100000),
    _d("risk.invalidation.maximum_events", int, "entries", 256, minimum=1, maximum=100000),
    _d("risk.invalidation.maximum_ledger_entries", int, "entries", 512, minimum=1, maximum=100000),
    _d("risk.invalidation.maximum_cache_entries", int, "entries", 256, minimum=1, maximum=100000),
    _d("risk.exit_management.enabled", bool, "boolean", True),
    _d("risk.exit_management.require_positive_exposure", bool, "boolean", True, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("risk.exit_management.invalidation_precedence", bool, "boolean", True, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("risk.exit_management.target_selection", str, "enum", "R_MULTIPLE_FIRST", choices=("STRUCTURE_FIRST","R_MULTIPLE_FIRST","NEAREST_VALID","FARTHEST_VALID","STRATEGY_DEFINED","COMPOSITE")),
    _d("risk.exit_management.duplicate_policy", str, "enum", "MERGE", choices=("MERGE","KEEP_HIGHEST_PRIORITY","REJECT_AMBIGUOUS")),
    _d("risk.exit_management.duplicate_tolerance", float, "normalized-distance", 0.00000001, minimum=0.0, maximum=1e9),
    _d("risk.exit_management.maximum_stages", int, "stages", 16, minimum=1, maximum=1000),
    _d("risk.exit_management.default_trigger", str, "enum", "CLOSE_AT_OR_BEYOND", choices=("TOUCH","CLOSE_AT_OR_BEYOND","MULTI_CLOSE","STRUCTURAL_CONFIRMATION","TIME_CONDITION","STRATEGY_DEFINED")),
    _d("risk.exit_management.same_bar_policy", str, "enum", "AMBIGUOUS_NO_RESULT", choices=("INVALIDATION_FIRST","AMBIGUOUS_NO_RESULT","USE_HIGHER_RESOLUTION_IF_AUTHORITATIVE")),
    _d("risk.exit_management.multi_target_policy", str, "enum", "PROCESS_IN_ORDER", choices=("PROCESS_IN_ORDER","COMBINE","AMBIGUOUS")),
    _d("risk.exit_management.residual_policy", str, "enum", "CLOSE_REMAINDER", choices=("CLOSE_REMAINDER","RETAIN_IF_VALID")),
    _d("risk.exit_management.exposure_step", float, "simulated-exposure-unit", 0.01, minimum=0.000000001, maximum=1e15),
    _d("risk.exit_management.minimum_residual", float, "simulated-exposure-unit", 0.01, minimum=0.0, maximum=1e15),
    _d("risk.exit_management.maximum_plans", int, "entries", 256, minimum=1, maximum=100000),
    _d("risk.exit_management.maximum_targets", int, "entries", 512, minimum=1, maximum=100000),
    _d("risk.exit_management.maximum_events", int, "entries", 512, minimum=1, maximum=100000),
    _d("risk.exit_management.maximum_ledger_entries", int, "entries", 1024, minimum=1, maximum=100000),
    _d("risk.exit_management.maximum_cache_entries", int, "entries", 256, minimum=1, maximum=100000),
    _d("risk.protective.enabled", bool, "boolean", True),
    _d("risk.protective.never_loosen", bool, "boolean", True, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("risk.protective.require_remaining_exposure", bool, "boolean", True, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("risk.protective.closed_observation_only", bool, "boolean", True, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("risk.protective.break_even_enabled", bool, "boolean", True),
    _d("risk.protective.break_even_activation", str, "enum", "NORMALIZED_R", choices=("NORMALIZED_R","TARGET_STAGE_COMPLETION","STRUCTURAL_PROGRESS","STRATEGY_DEFINED")),
    _d("risk.protective.break_even_threshold", float, "normalized-R", 1.0, minimum=0.000000001, maximum=1000.0),
    _d("risk.protective.break_even_offset_method", str, "enum", "NONE", choices=("NONE","NORMALIZED_FIXED","ATR_NORMALIZED","RESEARCH_FRICTION_AWARE","STRATEGY_DEFINED")),
    _d("risk.protective.break_even_offset", float, "normalized-distance", 0.0, minimum=0.0, maximum=1e9),
    _d("risk.protective.trailing_enabled", bool, "boolean", True),
    _d("risk.protective.trailing_activation", str, "enum", "BREAK_EVEN_ACTIVATED", choices=("NORMALIZED_R","TARGET_STAGE_COMPLETION","BREAK_EVEN_ACTIVATED","STRUCTURAL_PROGRESS","RUNNER_ACTIVATED","STRATEGY_DEFINED")),
    _d("risk.protective.trailing_threshold", float, "normalized-R", 1.0, minimum=0.0, maximum=1000.0),
    _d("risk.protective.atr_multiplier", float, "ATR-multiple", 2.0, minimum=0.000000001, maximum=1000.0),
    _d("risk.protective.hybrid_policy", str, "enum", "MOST_PROTECTIVE_VALID", choices=("MOST_PROTECTIVE_VALID","LEAST_AGGRESSIVE_VALID","STRUCTURE_PRIORITY","ATR_PRIORITY","R_PRIORITY","CONSENSUS_REQUIRED","STRATEGY_DEFINED")),
    _d("risk.protective.minimum_improvement", float, "normalized-distance", 0.01, minimum=0.0, maximum=1e9),
    _d("risk.protective.minimum_noise_distance", float, "normalized-distance", 0.0, minimum=0.0, maximum=1e9),
    _d("risk.protective.cooldown_seconds", int, "seconds", 0, minimum=0, maximum=31536000),
    _d("risk.protective.same_bar_policy", str, "enum", "USE_PRIOR_ACTIVE_BOUNDARY", choices=("AMBIGUOUS_NO_RESULT","USE_PRIOR_ACTIVE_BOUNDARY","USE_HIGHER_RESOLUTION_IF_AUTHORITATIVE","CONSERVATIVE_TERMINATION")),
    _d("risk.protective.maximum_candidates", int, "entries", 512, minimum=1, maximum=100000),
    _d("risk.protective.maximum_versions", int, "entries", 512, minimum=1, maximum=100000),
    _d("risk.protective.maximum_events", int, "entries", 512, minimum=1, maximum=100000),
    _d("risk.protective.maximum_ledger_entries", int, "entries", 1024, minimum=1, maximum=100000),
    _d("risk.protective.maximum_cache_entries", int, "entries", 256, minimum=1, maximum=100000),
    _d("portfolio.risk.enabled", bool, "boolean", True),
    _d("portfolio.risk.admission_policy", str, "enum", "BLOCK_IF_INSUFFICIENT", choices=("BLOCK_IF_INSUFFICIENT","REDUCE_TO_CAPACITY")),
    _d("portfolio.risk.require_complete_state", bool, "boolean", True, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("portfolio.risk.require_reservation", bool, "boolean", True, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("portfolio.risk.require_factor_decomposition", bool, "boolean", True, safety_critical=True, override_policy=OverridePolicy.RESTRICT_ONLY),
    _d("portfolio.risk.maximum_research_risk", float, "normalized-research-risk", 1000.0, minimum=0.0, maximum=1e15),
    _d("portfolio.risk.maximum_gross_exposure", float, "fictional-exposure-unit", 1000.0, minimum=0.0, maximum=1e15),
    _d("portfolio.risk.soft_risk_threshold", float, "normalized-research-risk", 800.0, minimum=0.0, maximum=1e15),
    _d("portfolio.risk.soft_gross_threshold", float, "fictional-exposure-unit", 800.0, minimum=0.0, maximum=1e15),
    _d("portfolio.risk.maximum_concurrent_hypotheses", int, "hypotheses", 8, minimum=1, maximum=100000),
    _d("portfolio.risk.maximum_bullish_exposure", float, "fictional-exposure-unit", 1000.0, minimum=0.0, maximum=1e15),
    _d("portfolio.risk.maximum_bearish_exposure", float, "fictional-exposure-unit", 1000.0, minimum=0.0, maximum=1e15),
    _d("portfolio.risk.maximum_directional_imbalance", float, "fictional-exposure-unit", 1000.0, minimum=0.0, maximum=1e15),
    _d("portfolio.risk.maximum_instrument_risk", float, "normalized-research-risk", 1000.0, minimum=0.0, maximum=1e15),
    _d("portfolio.risk.maximum_instrument_exposure", float, "fictional-exposure-unit", 1000.0, minimum=0.0, maximum=1e15),
    _d("portfolio.risk.maximum_concurrent_per_instrument", int, "hypotheses", 8, minimum=1, maximum=100000),
    _d("portfolio.risk.maximum_factor_gross", float, "fictional-exposure-unit", 1000.0, minimum=0.0, maximum=1e15),
    _d("portfolio.risk.maximum_factor_net", float, "fictional-exposure-unit", 1000.0, minimum=0.0, maximum=1e15),
    _d("portfolio.risk.maximum_strategy_exposure", float, "fictional-exposure-unit", 1000.0, minimum=0.0, maximum=1e15),
    _d("portfolio.risk.maximum_family_exposure", float, "fictional-exposure-unit", 1000.0, minimum=0.0, maximum=1e15),
    _d("portfolio.risk.maximum_variant_exposure", float, "fictional-exposure-unit", 1000.0, minimum=0.0, maximum=1e15),
    _d("portfolio.risk.minimum_exposure", float, "fictional-exposure-unit", 0.01, minimum=0.0, maximum=1e15),
    _d("portfolio.risk.exposure_step", float, "fictional-exposure-unit", 0.01, minimum=0.000000001, maximum=1e15),
    _d("portfolio.risk.reservation_ttl_seconds", int, "seconds", 300, minimum=1, maximum=31536000),
    _d("portfolio.risk.maximum_records", int, "entries", 512, minimum=1, maximum=100000),
    _d("portfolio.risk.maximum_reservations", int, "entries", 512, minimum=1, maximum=100000),
    _d("portfolio.risk.maximum_snapshots", int, "entries", 512, minimum=1, maximum=100000),
    _d("portfolio.risk.maximum_ledger_events", int, "entries", 1024, minimum=1, maximum=100000),
    _d("portfolio.risk.maximum_cache_entries", int, "entries", 256, minimum=1, maximum=100000),
    _d("optimization.enabled", bool, "boolean", False),
    _d("optimization.maximum_runs", int, "count", 100, minimum=1, maximum=10000),
    _d("simulation.enabled", bool, "boolean", False),
    _d("simulation.type", str, "enum", "FICTIONAL", choices=("FICTIONAL",)),
    _d("simulation.seed", int, "integer", DEFAULT_SEED, minimum=0, maximum=2**32 - 1),
    _d("persistence.checkpoint_mode", str, "enum", "HYBRID",
       choices=("EVENT", "PERIODIC", "HYBRID")),
    _d("persistence.minimum_interval_seconds", int, "seconds", 30, minimum=1, maximum=86400),
    _d("persistence.maximum_uncheckpointed_events", int, "count", 100, minimum=1, maximum=100000),
    _d("persistence.retention_generations", int, "count", 2, minimum=2, maximum=20),
    _d("persistence.maximum_checkpoint_bytes", int, "bytes", 1000000,
       minimum=1024, maximum=100000000),
    _d("execution.available", bool, "boolean", False, safety_critical=True,
       override_policy=OverridePolicy.DENY),
    _d("broker.live_execution", bool, "boolean", False, safety_critical=True,
       override_policy=OverridePolicy.DENY),
    _d("broker.demo_execution", bool, "boolean", False, safety_critical=True,
       override_policy=OverridePolicy.DENY),
    _d("broker.authentication", bool, "boolean", False, safety_critical=True,
       override_policy=OverridePolicy.DENY),
    _d("safety.unlimited_exposure", bool, "boolean", False, safety_critical=True,
       override_policy=OverridePolicy.DENY),
    _d("safety.martingale", bool, "boolean", False, safety_critical=True,
       override_policy=OverridePolicy.DENY),
    _d("legacy.timer_interval", int, "seconds", 60, deprecated_replacement="general.scheduler_seconds"),
)

SCHEMA = {definition.key: definition for definition in SETTING_DEFINITIONS}
HARD_SAFETY_VALUES = {
    definition.key: definition.default
    for definition in SETTING_DEFINITIONS
    if definition.override_policy is OverridePolicy.DENY
}
SECRET_KEY_FRAGMENTS = ("password", "secret", "credential", "api_key", "token")


def contains_secret_key(key: str) -> bool:
    lowered = key.lower()
    return any(fragment in lowered for fragment in SECRET_KEY_FRAGMENTS)
