AMRTE_VERSION = "0.27.0"
CONFIG_SCHEMA_VERSION = "1.0"
STATE_SCHEMA_VERSION = "1.0"
SIMULATION_SCHEMA_VERSION = "1.0"

DEFAULT_SEED = 20260919
DEFAULT_CONTEXT_TIMEFRAME = "H4"
DEFAULT_STRATEGY_TIMEFRAME = "H1"
DEFAULT_EXECUTION_TIMEFRAME = "M15"

LIVE_BROKER_EXECUTION_AVAILABLE = False
DEMO_BROKER_EXECUTION_AVAILABLE = False

# Absolute bounds for abstract, fictional research scenarios.
MAX_RESEARCH_RESOURCE_LOAD = 1.0
MAX_CONCURRENT_SCENARIOS = 8
